#include <stdio.h>
#include "end.h"

FUNCTION(test, void) START 
    VARIABLE("ayyy", str, CHAR POINTER) LINETERM
    VARIABLE(0, i, INT) LINETERM
    WHILE(i++ ST 10) START
        CALL(puts, GET(str)) LINETERM
    END
    REGISTER_VARIABLE(a, CHAR POINTER) LINETERM
    SET("end", a) LINETERM
    CALL(puts, GET(a)) LINETERM
    RET LINETERM
END 



FUNCTION(main, INT, INT argc, CHAR PPOINTER argv) START
    COMMENT VARIABLE("ayyy", str, CHAR POINTER) LINETERM
    COMMENT CALL(puts, GET(str)) LINETERM
    CALL(test) LINETERM
    RET 0 LINETERM
END 
